import React from 'react';
import styles from './styles.scss';

export default function Entry() {
  return (
    <div className={styles.entry}>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet, lectus ac accumsan pellentesque, mi diam fermentum neque, eu tincidunt sapien lacus luctus lectus. Sed sit amet placerat purus. Quisque vulputate nunc ut magna tempor, sed mattis tellus eleifend. Curabitur diam leo, ultrices quis nisi venenatis, vulputate auctor nisl. Donec enim felis, pulvinar mattis fringilla sed, auctor sollicitudin sapien. Pellentesque orci orci, porttitor et mollis a, elementum non tortor. Integer vulputate erat sapien, vitae laoreet magna dignissim non. In vel auctor arcu. Praesent urna enim, pretium sit amet tellus non, efficitur consequat tortor. Maecenas at dapibus nisi, a tempor dolor. Aliquam quis dui arcu. Duis pretium orci et nibh efficitur venenatis.

        In gravida nibh eros, id rutrum augue euismod non. Donec dictum sodales ex, at tristique dui laoreet eu. Suspendisse malesuada condimentum ligula id faucibus. Proin vulputate purus non magna luctus, eget suscipit diam efficitur. Nam eros massa, volutpat nec suscipit vitae, pellentesque nec sem. Suspendisse convallis sem faucibus semper pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam tempus arcu mi, in aliquet augue tristique id. Aliquam volutpat luctus lorem, tincidunt efficitur velit cursus at. Nulla commodo est eu ex gravida aliquet. Praesent auctor leo ut ante aliquet, ac dictum nisl mattis. Nullam sodales at ipsum vitae pharetra. Nulla nulla lectus, consectetur et mi eget, feugiat volutpat magna. Morbi dapibus, justo eu rutrum rutrum, ipsum ligula aliquet augue, eget dapibus nisl orci vel ex. Pellentesque dolor quam, laoreet eget scelerisque sed, vulputate ac erat.

        Integer vitae dolor sed magna iaculis tincidunt. Donec semper ornare auctor. Nullam vitae tempus dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vitae odio sit amet nisl porttitor ornare. Nam sed accumsan leo, sit amet tempus mi. Ut non eleifend mauris. Pellentesque dolor massa, lobortis non malesuada sit amet, porttitor sodales odio. Sed non congue enim, ac sagittis magna. Proin accumsan libero dolor, ut cursus lacus vulputate ac. Vivamus felis sapien, maximus eleifend lectus nec, egestas sollicitudin ligula. Aenean ut ligula vel metus consequat dignissim non et massa. Maecenas tellus magna, interdum non molestie ut, cursus ac nisi. Pellentesque eget semper massa.

        Aliquam erat volutpat. Vivamus ex dolor, ultricies at felis nec, hendrerit aliquam diam. Sed ac congue elit. Maecenas pharetra ante a dolor volutpat, eget egestas arcu scelerisque. Sed congue vehicula est eget iaculis. Sed sit amet erat non erat vehicula porttitor at et tellus. Ut sit amet eros sollicitudin, maximus justo in, condimentum metus. Pellentesque ullamcorper, nunc vehicula feugiat tempor, purus nunc commodo justo, sed laoreet libero nisi at erat. Quisque magna turpis, vulputate vitae dui vel, consequat aliquet metus. Integer ut mi rhoncus, rutrum turpis non, finibus nibh. Phasellus ut imperdiet orci, eget sodales magna. Nullam mattis bibendum nibh eu interdum. Fusce vulputate est vitae lacinia eleifend.

        Etiam molestie porta ante sit amet dapibus. Proin vel felis commodo, mattis orci in, sollicitudin odio. Ut sit amet est vel justo fringilla varius. Nam ullamcorper felis lectus, at elementum felis tempor non. Pellentesque ultricies blandit nisi, at volutpat turpis. Aenean lectus ante, facilisis a feugiat eget, dignissim sit amet arcu. Sed quis erat libero.
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet, lectus ac accumsan pellentesque, mi diam fermentum neque, eu tincidunt sapien lacus luctus lectus. Sed sit amet placerat purus. Quisque vulputate nunc ut magna tempor, sed mattis tellus eleifend. Curabitur diam leo, ultrices quis nisi venenatis, vulputate auctor nisl. Donec enim felis, pulvinar mattis fringilla sed, auctor sollicitudin sapien. Pellentesque orci orci, porttitor et mollis a, elementum non tortor. Integer vulputate erat sapien, vitae laoreet magna dignissim non. In vel auctor arcu. Praesent urna enim, pretium sit amet tellus non, efficitur consequat tortor. Maecenas at dapibus nisi, a tempor dolor. Aliquam quis dui arcu. Duis pretium orci et nibh efficitur venenatis.

        In gravida nibh eros, id rutrum augue euismod non. Donec dictum sodales ex, at tristique dui laoreet eu. Suspendisse malesuada condimentum ligula id faucibus. Proin vulputate purus non magna luctus, eget suscipit diam efficitur. Nam eros massa, volutpat nec suscipit vitae, pellentesque nec sem. Suspendisse convallis sem faucibus semper pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam tempus arcu mi, in aliquet augue tristique id. Aliquam volutpat luctus lorem, tincidunt efficitur velit cursus at. Nulla commodo est eu ex gravida aliquet. Praesent auctor leo ut ante aliquet, ac dictum nisl mattis. Nullam sodales at ipsum vitae pharetra. Nulla nulla lectus, consectetur et mi eget, feugiat volutpat magna. Morbi dapibus, justo eu rutrum rutrum, ipsum ligula aliquet augue, eget dapibus nisl orci vel ex. Pellentesque dolor quam, laoreet eget scelerisque sed, vulputate ac erat.

        Integer vitae dolor sed magna iaculis tincidunt. Donec semper ornare auctor. Nullam vitae tempus dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vitae odio sit amet nisl porttitor ornare. Nam sed accumsan leo, sit amet tempus mi. Ut non eleifend mauris. Pellentesque dolor massa, lobortis non malesuada sit amet, porttitor sodales odio. Sed non congue enim, ac sagittis magna. Proin accumsan libero dolor, ut cursus lacus vulputate ac. Vivamus felis sapien, maximus eleifend lectus nec, egestas sollicitudin ligula. Aenean ut ligula vel metus consequat dignissim non et massa. Maecenas tellus magna, interdum non molestie ut, cursus ac nisi. Pellentesque eget semper massa.

        Aliquam erat volutpat. Vivamus ex dolor, ultricies at felis nec, hendrerit aliquam diam. Sed ac congue elit. Maecenas pharetra ante a dolor volutpat, eget egestas arcu scelerisque. Sed congue vehicula est eget iaculis. Sed sit amet erat non erat vehicula porttitor at et tellus. Ut sit amet eros sollicitudin, maximus justo in, condimentum metus. Pellentesque ullamcorper, nunc vehicula feugiat tempor, purus nunc commodo justo, sed laoreet libero nisi at erat. Quisque magna turpis, vulputate vitae dui vel, consequat aliquet metus. Integer ut mi rhoncus, rutrum turpis non, finibus nibh. Phasellus ut imperdiet orci, eget sodales magna. Nullam mattis bibendum nibh eu interdum. Fusce vulputate est vitae lacinia eleifend.

        Etiam molestie porta ante sit amet dapibus. Proin vel felis commodo, mattis orci in, sollicitudin odio. Ut sit amet est vel justo fringilla varius. Nam ullamcorper felis lectus, at elementum felis tempor non. Pellentesque ultricies blandit nisi, at volutpat turpis. Aenean lectus ante, facilisis a feugiat eget, dignissim sit amet arcu. Sed quis erat libero.
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet, lectus ac accumsan pellentesque, mi diam fermentum neque, eu tincidunt sapien lacus luctus lectus. Sed sit amet placerat purus. Quisque vulputate nunc ut magna tempor, sed mattis tellus eleifend. Curabitur diam leo, ultrices quis nisi venenatis, vulputate auctor nisl. Donec enim felis, pulvinar mattis fringilla sed, auctor sollicitudin sapien. Pellentesque orci orci, porttitor et mollis a, elementum non tortor. Integer vulputate erat sapien, vitae laoreet magna dignissim non. In vel auctor arcu. Praesent urna enim, pretium sit amet tellus non, efficitur consequat tortor. Maecenas at dapibus nisi, a tempor dolor. Aliquam quis dui arcu. Duis pretium orci et nibh efficitur venenatis.

        In gravida nibh eros, id rutrum augue euismod non. Donec dictum sodales ex, at tristique dui laoreet eu. Suspendisse malesuada condimentum ligula id faucibus. Proin vulputate purus non magna luctus, eget suscipit diam efficitur. Nam eros massa, volutpat nec suscipit vitae, pellentesque nec sem. Suspendisse convallis sem faucibus semper pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam tempus arcu mi, in aliquet augue tristique id. Aliquam volutpat luctus lorem, tincidunt efficitur velit cursus at. Nulla commodo est eu ex gravida aliquet. Praesent auctor leo ut ante aliquet, ac dictum nisl mattis. Nullam sodales at ipsum vitae pharetra. Nulla nulla lectus, consectetur et mi eget, feugiat volutpat magna. Morbi dapibus, justo eu rutrum rutrum, ipsum ligula aliquet augue, eget dapibus nisl orci vel ex. Pellentesque dolor quam, laoreet eget scelerisque sed, vulputate ac erat.

        Integer vitae dolor sed magna iaculis tincidunt. Donec semper ornare auctor. Nullam vitae tempus dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vitae odio sit amet nisl porttitor ornare. Nam sed accumsan leo, sit amet tempus mi. Ut non eleifend mauris. Pellentesque dolor massa, lobortis non malesuada sit amet, porttitor sodales odio. Sed non congue enim, ac sagittis magna. Proin accumsan libero dolor, ut cursus lacus vulputate ac. Vivamus felis sapien, maximus eleifend lectus nec, egestas sollicitudin ligula. Aenean ut ligula vel metus consequat dignissim non et massa. Maecenas tellus magna, interdum non molestie ut, cursus ac nisi. Pellentesque eget semper massa.

        Aliquam erat volutpat. Vivamus ex dolor, ultricies at felis nec, hendrerit aliquam diam. Sed ac congue elit. Maecenas pharetra ante a dolor volutpat, eget egestas arcu scelerisque. Sed congue vehicula est eget iaculis. Sed sit amet erat non erat vehicula porttitor at et tellus. Ut sit amet eros sollicitudin, maximus justo in, condimentum metus. Pellentesque ullamcorper, nunc vehicula feugiat tempor, purus nunc commodo justo, sed laoreet libero nisi at erat. Quisque magna turpis, vulputate vitae dui vel, consequat aliquet metus. Integer ut mi rhoncus, rutrum turpis non, finibus nibh. Phasellus ut imperdiet orci, eget sodales magna. Nullam mattis bibendum nibh eu interdum. Fusce vulputate est vitae lacinia eleifend.

        Etiam molestie porta ante sit amet dapibus. Proin vel felis commodo, mattis orci in, sollicitudin odio. Ut sit amet est vel justo fringilla varius. Nam ullamcorper felis lectus, at elementum felis tempor non. Pellentesque ultricies blandit nisi, at volutpat turpis. Aenean lectus ante, facilisis a feugiat eget, dignissim sit amet arcu. Sed quis erat libero.
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet, lectus ac accumsan pellentesque, mi diam fermentum neque, eu tincidunt sapien lacus luctus lectus. Sed sit amet placerat purus. Quisque vulputate nunc ut magna tempor, sed mattis tellus eleifend. Curabitur diam leo, ultrices quis nisi venenatis, vulputate auctor nisl. Donec enim felis, pulvinar mattis fringilla sed, auctor sollicitudin sapien. Pellentesque orci orci, porttitor et mollis a, elementum non tortor. Integer vulputate erat sapien, vitae laoreet magna dignissim non. In vel auctor arcu. Praesent urna enim, pretium sit amet tellus non, efficitur consequat tortor. Maecenas at dapibus nisi, a tempor dolor. Aliquam quis dui arcu. Duis pretium orci et nibh efficitur venenatis.

        In gravida nibh eros, id rutrum augue euismod non. Donec dictum sodales ex, at tristique dui laoreet eu. Suspendisse malesuada condimentum ligula id faucibus. Proin vulputate purus non magna luctus, eget suscipit diam efficitur. Nam eros massa, volutpat nec suscipit vitae, pellentesque nec sem. Suspendisse convallis sem faucibus semper pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam tempus arcu mi, in aliquet augue tristique id. Aliquam volutpat luctus lorem, tincidunt efficitur velit cursus at. Nulla commodo est eu ex gravida aliquet. Praesent auctor leo ut ante aliquet, ac dictum nisl mattis. Nullam sodales at ipsum vitae pharetra. Nulla nulla lectus, consectetur et mi eget, feugiat volutpat magna. Morbi dapibus, justo eu rutrum rutrum, ipsum ligula aliquet augue, eget dapibus nisl orci vel ex. Pellentesque dolor quam, laoreet eget scelerisque sed, vulputate ac erat.

        Integer vitae dolor sed magna iaculis tincidunt. Donec semper ornare auctor. Nullam vitae tempus dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vitae odio sit amet nisl porttitor ornare. Nam sed accumsan leo, sit amet tempus mi. Ut non eleifend mauris. Pellentesque dolor massa, lobortis non malesuada sit amet, porttitor sodales odio. Sed non congue enim, ac sagittis magna. Proin accumsan libero dolor, ut cursus lacus vulputate ac. Vivamus felis sapien, maximus eleifend lectus nec, egestas sollicitudin ligula. Aenean ut ligula vel metus consequat dignissim non et massa. Maecenas tellus magna, interdum non molestie ut, cursus ac nisi. Pellentesque eget semper massa.

        Aliquam erat volutpat. Vivamus ex dolor, ultricies at felis nec, hendrerit aliquam diam. Sed ac congue elit. Maecenas pharetra ante a dolor volutpat, eget egestas arcu scelerisque. Sed congue vehicula est eget iaculis. Sed sit amet erat non erat vehicula porttitor at et tellus. Ut sit amet eros sollicitudin, maximus justo in, condimentum metus. Pellentesque ullamcorper, nunc vehicula feugiat tempor, purus nunc commodo justo, sed laoreet libero nisi at erat. Quisque magna turpis, vulputate vitae dui vel, consequat aliquet metus. Integer ut mi rhoncus, rutrum turpis non, finibus nibh. Phasellus ut imperdiet orci, eget sodales magna. Nullam mattis bibendum nibh eu interdum. Fusce vulputate est vitae lacinia eleifend.

        Etiam molestie porta ante sit amet dapibus. Proin vel felis commodo, mattis orci in, sollicitudin odio. Ut sit amet est vel justo fringilla varius. Nam ullamcorper felis lectus, at elementum felis tempor non. Pellentesque ultricies blandit nisi, at volutpat turpis. Aenean lectus ante, facilisis a feugiat eget, dignissim sit amet arcu. Sed quis erat libero.
      </p>
    </div>
  );
}
